---
title: "Replikation"
author: "Thomas Reumiller"
date: "9 10 2023"
output: html_document
---
ToDos

Fehler stimmen nicht x2
Einige Ergebnisse stimmen nicht mit plots 端berein
Legenden


writeClipboard(paste0('"',colnames(data)[142:156],'"', collapse=", "))


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(haven)
library(dplyr)
library(ggplot2)
library(sandwich) # f端r NeweyWest
library(ggpubr) # f端r ggarrange

```


Daten einlesen
```{r}
data = read_dta('Setting_Sun_dataset.dta')
data = data[order(data$hour),]
data$id = 1:nrow(data)
data = mutate(data, resid_renewables = renewables - solar - wind)
```

```{r}
head(data)
```



```{r}
dat = data %>%
  group_by(hour, year) %>%
  summarise(load = mean(load),solar =  mean(solar),price = median(rtm_total_lmp, na.rm = TRUE),wind = mean(wind))

```

```{r}
ggplot() +
  geom_line(data = filter(dat,year == 2016), aes(x = hour, y = load))+
  geom_line(data = filter(dat,year == 2013), aes(x = hour, y = load))

ggplot() +
  geom_line(data = filter(dat,year == 2016), aes(x = hour, y = solar))+
  geom_line(data = filter(dat,year == 2013), aes(x = hour, y = solar))

ggplot() +
  geom_line(data = filter(dat,year == 2013), aes(x = hour, y = price))+
  geom_line(data = filter(dat,year == 2016), aes(x = hour, y = price))+
  ylim(0,60)

ggplot() +
  geom_line(data = filter(dat,year == 2016), aes(x = hour, y = wind))+
  geom_line(data = filter(dat,year == 2013), aes(x = hour, y = wind))
  
```

Abbildung 2

```{r}
# Ergebnis-DF initialisieren
output_1 =
  data.frame(
    hour = 1:24,
    beta_solar = NA,
    beta_wind = NA,
    beta_spot = NA,
    stddev_solar = NA,
    stddev_wind = NA,
    stddev_spot = NA
  )

# Schleife 端ber Stunden
for (h in 1:24) {
  # Modell anpassen
  formel = formula(rtm_total_lmp ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month))
  ols = lm(formel, data = data[data$hour == h, ])
  
  # Koeffizienten und Standardfehler speichern
  output_1[h,2] = coef(ols)[2]
  output_1[h,3] = coef(ols)[3]
  output_1[h,4] = coef(ols)[4]
  nw_error = sqrt(diag(NeweyWest(ols, lag = 7, prewhite = FALSE)))
  output_1[h,5] = nw_error[2]
  output_1[h,6] = nw_error[3]
  output_1[h,7] = nw_error[4]
  #cov_raw = NeweyWest(ols, lag = 7, prewhite = FALSE, adjust=TRUE, verbose=TRUE)
  #std_raw = chol(cov_raw)
  #std = diag(std_raw)
  #output_1[h,5] = std[2]
  #output_1[h,6] = std[3]
  #output_1[h,7] = std[4]
}


output_1
```

```{r}
figure2_a = ggplot(output_1, aes(x = hour)) +
  geom_point(aes(y = beta_solar),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_solar+2*stddev_solar, ymin = beta_solar-2*stddev_solar), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Avg. Hourly Price \n ($/MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-0.8,0.6), breaks = seq(-0.8,0.6,0.2)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))


figure2_b = ggplot(output_1, aes(x = hour)) +
  geom_point(aes(y = beta_wind),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_wind+2*stddev_wind, ymin = beta_wind-2*stddev_wind), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Avg. Hourly Price \n ($/MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-0.6,0.2)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))


figure2_c = ggplot(output_1, aes(x = hour)) +
  geom_point(aes(y = beta_spot),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_spot+2*stddev_spot, ymin = beta_spot-2*stddev_spot), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Avg. Hourly Price \n ($/MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(0,16), breaks = seq(0,16,2)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))


figure2 = ggarrange(figure2_a, figure2_b, figure2_c,
                    labels = c("a", "b", "c"),
                    ncol = 1, nrow = 3)
figure2

```

Table 1

```{r}

tab1 = data.frame('Source' = c("Thermal","Nuclear", "Large hydroelectric", "Solar", "Wind", "Other Renewables", "Net imports"),
                  'Average Hourly Quantity Supplied (MWh)' = c(round(mean(data$thermal, na.rm = TRUE)), round(mean(data$nuclear)), round(mean(data$large_hydro)), round(mean(data$solar)), round(mean(data$wind)), round(mean(data$resid_renewables, na.rm = TRUE)), round(mean(data$imports))),
                  'SD (MWh)' = c(round(sd(data$thermal, na.rm = TRUE)), round(sd(data$nuclear)), round(sd(data$large_hydro)), round(sd(data$solar)), round(sd(data$wind)), round(sd(data$resid_renewables, na.rm = TRUE)), round(sd(data$imports))))
tab1
```


Figure 3a

```{r}

formulas = c(
            formula(thermal ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(nuclear ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(large_hydro ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(imports ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(resid_renewables ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)))


name = c("thermal",
         "nuclear",
         "large_hydro",
         "imports",
         "resid_renewables")
i = 0

for (formel in formulas) {
  
  output = data.frame(
    hour = 1:24,
    beta_solar = NA,
    beta_wind = NA,
    stddev_solar = NA,
    stddev_wind = NA)
  
  for (h in 1:24) {
    ols = lm(formel, data = data[data$hour == h,])
    
    output[h,2] = coef(ols)[2]
    output[h,3] = coef(ols)[3]
    nw_error = sqrt(diag(NeweyWest(ols, lag = 7, prewhite = FALSE)))
    output[h,4] = nw_error[2]
    output[h,5] = nw_error[3]
  }

  i = i + 1
  assign(paste(name[i], "_change", sep = ""),  output)
}


```


Figure 3b

```{r}

formulas = c(
            formula(net_load_ccgt_caiso ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(net_load_gt_caiso ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)),
            formula(net_load_st_caiso ~ daily_solar + daily_wind + spot + load + inches_lag + as.factor(month)))

name = c("ccgt",
         "gt",
         "st")
i = 0

for (formel in formulas) {
  
  output = data.frame(
    hour = 1:24,
    beta_solar = NA,
    stddev_solar = NA)

  for (h in 1:24) {
    ols = lm(formel, data = data[data$hour == h,])
    
    output[h,2] = coef(ols)[2]
    nw_error = sqrt(diag(NeweyWest(ols, lag = 7, prewhite = FALSE)))
    output[h,3] = nw_error[2]
  }
  
  i = i + 1
  assign(paste(name[i], "_change", sep = ""),  output)
  
}
```


figure3a
```{r}

dotsize = 2
linesize = 0.5
color = c("blue","red","green","black","grey")

colnames(resid_renewables_change) = c("hour", "beta_solar", "beta_wind", "stddev_solar", "stddev_wind") 
colnames(resid_renewables_change) = paste(colnames(resid_renewables_change),"resid_renewables",sep="_")
colnames(resid_renewables_change)[1] = "hour"

df = merge(thermal_change,nuclear_change,by = "hour",suffixes = c("_thermal","_nuclear")) %>% 
  merge(large_hydro_change,by = "hour") %>% 
  merge(imports_change,by = "hour",suffixes = c("_large_hydro","_imports")) %>% 
  merge(resid_renewables_change,by = "hour")

figure3_a =  ggplot(df, aes(x = hour)) +
  geom_point(aes(y = beta_solar_thermal),color = color[1], size = dotsize) +
  geom_line(aes(y = beta_solar_thermal),color = color[1], size = linesize)+
  geom_point(aes(y = beta_solar_nuclear),color = color[2], size = dotsize) +
  geom_line(aes(y = beta_solar_nuclear),color = color[2], size = linesize)+
  geom_point(aes(y = beta_solar_large_hydro),color = color[3], size = dotsize) +
  geom_line(aes(y = beta_solar_large_hydro),color = color[3], size = linesize)+
  geom_point(aes(y = beta_solar_imports),color = color[4], size = dotsize) +
  geom_line(aes(y = beta_solar_imports),color = color[4], size = linesize)+
  geom_point(aes(y = beta_solar_resid_renewables),color = color[5], size = dotsize) +
  geom_line(aes(y = beta_solar_resid_renewables),color = color[5], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly Generation (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-60,20), breaks = seq(-60,20,10)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure3_a

```
figure3_b
```{r}
dotsize = 2
linesize = 0.5
color = c("blue","red","green")

colnames(ccgt_change) = c("hour", "beta_solar", "stddev_solar") 
colnames(ccgt_change) = paste(colnames(ccgt_change),"ccgt",sep="_")
colnames(ccgt_change)[1] = "hour"

df = merge(gt_change,st_change,by = "hour",suffixes = c("_gt","_st")) %>% 
  merge(ccgt_change,by = "hour")

figure3_b =  ggplot(df, aes(x = hour)) +
  geom_point(aes(y = beta_solar_ccgt),color = color[1], size = dotsize) +
  geom_line(aes(y = beta_solar_ccgt),color = color[1], size = linesize)+
  geom_point(aes(y = beta_solar_gt),color = color[2], size = dotsize) +
  geom_line(aes(y = beta_solar_gt),color = color[2], size = linesize)+
  geom_point(aes(y = beta_solar_st),color = color[3], size = dotsize) +
  geom_line(aes(y = beta_solar_st),color = color[3], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly Generation (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  
  scale_y_continuous(limits = c(-35,10), breaks = seq(-35,10,5)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure3_b
```

Table 2
leider keine Daten



```{r}
data = data %>% 
  mutate(season = case_when(
     month <= 2 | month >= 12 ~ 1,    
     month >= 3 & month <= 5 ~ 2,
     month >= 6 & month <= 8 ~ 3,
     month >= 9 & month <= 11 ~ 4
  ))

```


```{r}

output_3a = data.frame("Winter" = NA, "Spring" = NA, "Summer" = NA , "Fall" = NA)
output_3b_co2 = data.frame(
  "hour" = 1:24,
  "beta_solar_winter" = NA,
  "beta_solar_std_winter" = NA,
  "beta_solar_spring" = NA,
  "beta_solar_std_spring" = NA,
  "beta_solar_summer" = NA,
  "beta_solar_std_summer" = NA,
  "beta_solar_fall" = NA,
  "beta_solar_std_fall" = NA
)

output_3b_supply = data.frame(
  "hour" = 1:24,
  "beta_solar_winter_hydro" = NA,
  "beta_solar_winter_imports" = NA,
  "beta_solar_winter_hydro_imports" = NA,
  "beta_solar_spring_hydro" = NA,
  "beta_solar_spring_imports" = NA,
  "beta_solar_spring_hydro_imports" = NA,
  "beta_solar_summer_hydro" = NA,
  "beta_solar_summer_imports" = NA,
  "beta_solar_summer_hydro_imports" = NA,
  "beta_solar_fall_hydro" = NA,
  "beta_solar_fall_imports" = NA,
  "beta_solar_fall_hydro_imports" = NA
)

for (s in 1:4) {
  
  dat = filter(data, season == s)
  dat = mutate(dat, hydro_imports = large_hydro + imports)

  dat = dat[order(dat$year, dat$month ,dat$day ,dat$hour), ]
  dat$id2 = 1:nrow(dat)
  for (m in 1:12) {
    dat = dat %>% 
    mutate(!!paste("m_", toString(m), sep = "") := ifelse(month == m, 1, 0))
  }
  for (h in 1:24) {
  dat = dat %>% 
    mutate(!!paste("daily_solar_h", toString(h), sep = "") := ifelse(hour == h, daily_solar, 0),
           !!paste("daily_wind_h", toString(h), sep = "") := ifelse(hour == h, daily_wind, 0),
           !!paste("spot_h", toString(h), sep = "") := ifelse(hour == h, spot, 0),
           !!paste("inches_lag_h", toString(h), sep = "") := ifelse(hour == h, inches_lag, 0),
           !!paste("load_h", toString(h), sep = "") := ifelse(hour == h, load, 0),
           !!paste("h_", toString(h), sep = "") := ifelse(hour == h, 1, 0))
  
    for (m in 1:12) {
      dat = dat %>% 
      mutate(!!paste(paste("m", toString(m), sep = ""),paste("h", toString(h), sep = ""), sep = "_") := ifelse(month == m & hour == h, 1, 0))
    }
  }
  
  formel_solar = paste("daily_solar_h", 1:24, sep = "", collapse = " + ")
  formel_wind = paste("daily_wind_h", 1:24, sep = "", collapse = " + ")
  formel_spot = paste("spot_h", 1:24, sep = "", collapse = " + ")
  formel_inches_lag = paste("inches_lag_h", 1:24, sep = "", collapse = " + ")
  formel_load = paste("load_h", 1:24, sep = "", collapse = " + ")
  formel_m_h = paste(colnames(dat[,grep("^m[1-9][0-9]?_h[1-9][0-9]?$", colnames(dat))]), sep = "", collapse = " + ")
  formel_rhs = paste(formel_solar,formel_wind,formel_spot,formel_inches_lag,formel_load,formel_m_h, sep = " + ")
  
  formel = paste("co2_caiso ~ ", formel_rhs)
  
  ols = lm(formel, data = dat)
  
  #eigentlich lag 168
  nw = NeweyWest(ols, lag = 7, prewhite = FALSE)
  nw_error = sqrt(diag(nw))
  
  output_3b_co2[,s*2] = coef(ols)[2:25]
  output_3b_co2[,s*2+1] = nw_error[2:25]

  co2_s = sum(coef(ols)[2:25])
  co2_s_std = sqrt(sum(diag(nw)[2:25]))
  
  output_3a[1,s] = co2_s
  output_3a[2,s] = co2_s_std
  
  #--------------------------------------------------------------------------------------------------------------------------------------------------
  

  formel = paste("large_hydro ~ ", formel_rhs)
  
  ols = lm(formel, data = dat)

  nw = NeweyWest(ols, lag = 7, prewhite = FALSE)
  nw_error = sqrt(diag(nw))
  
  output_3b_supply[,3*(s-1)+2] = coef(ols)[2:25]
  
  large_hydro_s = sum(coef(ols)[2:25])
  large_hydro_s_std = sqrt(sum(diag(nw)[2:25]))
    
  output_3a[5,s] = large_hydro_s
  output_3a[6,s] = large_hydro_s_std
  
  #--------------------------------------------------------------------------------------------------------------------------------------------------
  
  formel = paste("imports ~ ", formel_rhs)
  
  ols = lm(formel, data = dat)

  nw = NeweyWest(ols, lag = 7, prewhite = FALSE)
  nw_error = sqrt(diag(nw))
  
  output_3b_supply[,3*(s-1)+3] = coef(ols)[2:25]

  imports_s = sum(coef(ols)[2:25])
  imports_s_std = sqrt(sum(diag(nw)[2:25]))
  
  output_3a[7,s] = imports_s
  output_3a[8,s] = imports_s_std
  
  #--------------------------------------------------------------------------------------------------------------------------------------------------
  
  formel = paste("hydro_imports ~ ", formel_rhs)
  
  ols = lm(formel, data = dat)

  nw = NeweyWest(ols, lag = 7, prewhite = FALSE)
  nw_error = sqrt(diag(nw))
  
  output_3b_supply[,3*(s-1)+4] = coef(ols)[2:25]
  
  hydro_imports_s = sum(coef(ols)[2:25])
  hydro_imports_s_std = sqrt(sum(diag(nw)[2:25]))
    
  output_3a[9,s] = hydro_imports_s
  output_3a[10,s] = hydro_imports_s_std
  
  #--------------------------------------------------------------------------------------------------------------------------------------------------

  formel = paste("nox_caiso ~ ", formel_rhs)
  
  ols = lm(formel, data = dat)

  nw = NeweyWest(ols, lag = 7, prewhite = FALSE)
  nw_error = sqrt(diag(nw))
  
  nox_s = sum(coef(ols)[2:25])
  nox_s_std = sqrt(sum(diag(nw)[2:25]))
    
  output_3a[3,s] = nox_s
  output_3a[4,s] = nox_s_std
}
```

eventuell bei Fehler sum und sqrt vertauschen

```{r}

figure4_a = ggplot(output_3b_co2, aes(x = hour)) +
  geom_point(aes(y = beta_solar_winter),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_solar_winter+2*beta_solar_std_winter, ymin = beta_solar_winter-2*beta_solar_std_winter), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly CO2 (tons)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-50,20), breaks = seq(-50,20,10)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure4_a
```



```{r}

figure4_b = ggplot(output_3b_co2, aes(x = hour)) +
  geom_point(aes(y = beta_solar_spring),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_solar_spring+2*beta_solar_std_spring, ymin = beta_solar_spring-2*beta_solar_std_spring), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly CO2 (tons)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-50,20), breaks = seq(-50,20,10)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure4_b
```


```{r}

figure4_c = ggplot(output_3b_co2, aes(x = hour)) +
  geom_point(aes(y = beta_solar_summer),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_solar_summer+2*beta_solar_std_summer, ymin = beta_solar_summer-2*beta_solar_std_summer), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly CO2 (tons)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-50,20), breaks = seq(-50,20,10)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure4_c
```


```{r}

figure4_d = ggplot(output_3b_co2, aes(x = hour)) +
  geom_point(aes(y = beta_solar_fall),color = "grey", size = 3) +
  geom_errorbar(aes(ymax = beta_solar_fall+2*beta_solar_std_fall, ymin = beta_solar_fall-2*beta_solar_std_fall), size = 0.5) +
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly CO2 (tons)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-50,20), breaks = seq(-50,20,10)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure4_d
```

Die Werte passen jedoch die Fehler gar nicht


figure5_a
```{r}
linesize = 1
color = c("blue","red","green")


figure5a =  ggplot(output_3b_supply, aes(x = hour)) +
  geom_line(aes(y = beta_solar_winter_hydro),color = color[1], size = linesize)+
  geom_line(aes(y = beta_solar_winter_imports),color = color[2], size = linesize)+
  geom_line(aes(y = beta_solar_winter_hydro_imports),color = color[3], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Quantity Supplied (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-60,40), breaks = seq(-60,40,20)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure5a

```

figure5_b
```{r}
linesize = 1
color = c("blue","red","green")


figure5b =  ggplot(output_3b_supply, aes(x = hour)) +
  geom_line(aes(y = beta_solar_spring_hydro),color = color[1], size = linesize)+
  geom_line(aes(y = beta_solar_spring_imports),color = color[2], size = linesize)+
  geom_line(aes(y = beta_solar_spring_hydro_imports),color = color[3], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Quantity Supplied (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-60,40), breaks = seq(-60,40,20)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure5b

```

figure5_c
```{r}
linesize = 1
color = c("blue","red","green")


figure5c =  ggplot(output_3b_supply, aes(x = hour)) +
  geom_line(aes(y = beta_solar_summer_hydro),color = color[1], size = linesize)+
  geom_line(aes(y = beta_solar_summer_imports),color = color[2], size = linesize)+
  geom_line(aes(y = beta_solar_summer_hydro_imports),color = color[3], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Quantity Supplied (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-60,40), breaks = seq(-60,40,20)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure5c

```

figure5_d
```{r}
linesize = 1
color = c("blue","red","green")


figure5d =  ggplot(output_3b_supply, aes(x = hour)) +
  geom_line(aes(y = beta_solar_fall_hydro),color = color[1], size = linesize)+
  geom_line(aes(y = beta_solar_fall_imports),color = color[2], size = linesize)+
  geom_line(aes(y = beta_solar_fall_hydro_imports),color = color[3], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Change in Quantity Supplied (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(-60,40), breaks = seq(-60,40,20)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))

figure5d

```




