---
title: "Replikation_4"
author: "Thomas Reumiller"
date: "21 10 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(haven)
library(dplyr)
library(ggplot2)
library(fixest)
library(sandwich) # für NeweyWest
library(ggpubr) # für ggarrange
library(AER)
library(stats)
```


Daten einlesen
```{r}
data = read_dta('Setting_Sun_dataset.dta')

data = data %>% 
  mutate(season = case_when(
     month <= 2 | month >= 12 ~ 1,    
     month >= 3 & month <= 5 ~ 2,
     month >= 6 & month <= 8 ~ 3,
     month >= 9 & month <= 11 ~ 4
  ))


#unnütz?
data <- data %>%
  arrange(hour) %>%
  mutate(id = row_number())
```


Counterfaktische DAM Preise

```{r}
dat = mutate(data,
  solar_cap_factor = solar_potential / (24 * solar_cap / 1000),
  wind_cap_factor = wind_potential / (24 * wind_cap / 1000))

for (m in 1:12) {
  dat = dat %>% 
  mutate(!!paste("m_", toString(m), sep = "") := ifelse(month == m, 1, 0))
}
for (h in 1:24) {
  dat = dat %>% 
    mutate(!!paste("daily_solar_h", toString(h), sep = "") := ifelse(hour == h, daily_solar, 0),
           !!paste("daily_wind_h", toString(h), sep = "") := ifelse(hour == h, daily_wind, 0),
           !!paste("spot_h", toString(h), sep = "") := ifelse(hour == h, spot, 0),
           !!paste("inches_lag_h", toString(h), sep = "") := ifelse(hour == h, inches_lag, 0),
           !!paste("load_h", toString(h), sep = "") := ifelse(hour == h, load, 0),
           !!paste("h_", toString(h), sep = "") := ifelse(hour == h, 1, 0))
}


dat_actual = dat
dat_actual$solar_sample = "actual"

dat_2k = dat
dat_2k$solar_potential = dat$solar_cap_factor * 2000 * (24 / 1000)
dat_2k$solar_sample = "solar_2k"

dat_6k = dat
dat_6k$solar_potential = dat$solar_cap_factor * 6000 * (24 / 1000)
dat_6k$solar_sample = "solar_6k"

dat_10k = dat
dat_10k$solar_potential = dat$solar_cap_factor * 10000 * (24 / 1000)
dat_10k$solar_sample = "solar_10k"

dat_all = rbind(dat_actual, dat_2k, dat_6k, dat_10k)

dat_all$solar_load = dat_all$solar_potential * dat_all$daily_load

formel_m = paste("m_", 1:11, sep = "", collapse = " + ")
formel = formula(paste("solar_curtailed ~ solar_potential + solar_load + daily_wind + spot + daily_load + inches_lag +", formel_m))

fit = tobit(formel, left = 0, data = filter(dat_all, hour == 12 & solar_sample == "actual"))

dat_all$solar_curtailed_fitted = NA
dat_all$solar_curtailed_fitted =  predict(fit, newdata = dat_all)
dat_all$solar_curtailed_fitted[dat_all$solar_curtailed_fitted < 0] = 0

dat_all = mutate(dat_all, daily_solar = ifelse(solar_sample != "actual", solar_potential - solar_curtailed_fitted, daily_solar))


for (h in 1:24) {
 dat_all = mutate(dat_all, !!paste("daily_solar_h", toString(h), sep = "") := case_when(
   (hour == h) ~ daily_solar,
   .default = 0
 ))
}

formel_solar = paste("daily_solar_h", 1:24, sep = "", collapse = " + ")
formel_wind = paste("daily_wind_h", 1:24, sep = "", collapse = " + ")
formel_spot = paste("spot_h", 1:24, sep = "", collapse = " + ")
formel_inches_lag = paste("inches_lag_h", 1:24, sep = "", collapse = " + ")
formel_load = paste("load_h", 1:24, sep = "", collapse = " + ")
formel_hour = paste("h_", 1:24, sep = "", collapse = " + ")

formel_rhs = paste(formel_solar,formel_wind,formel_spot,formel_inches_lag,formel_load, formel_hour,"inches_lag_h1", sep = " + ")
formel = paste("dam_total_lmp ~ ", formel_rhs)

dat_all <- dat_all %>%
  mutate(dam_fitted = NA,
         resid = NA)

for (s in 1:4) {
  
  fit = lm(formel,data = filter(dat_all, solar_sample == "actual" & season == s))
  
  dat_all[dat_all$season == s,]$dam_fitted = predict(fit, newdata = filter(dat_all, season == s))
  dat_all[dat_all$season == s & dat_all$solar_sample == "actual" & !is.na(dat_all$dam_total_lmp),]$resid = residuals(fit)
  
}

dat_all[dat_all$solar_sample == "solar_2k",]$resid = dat_all[dat_all$solar_sample == "actual",]$resid
dat_all[dat_all$solar_sample == "solar_6k",]$resid = dat_all[dat_all$solar_sample == "actual",]$resid
dat_all[dat_all$solar_sample == "solar_10k",]$resid = dat_all[dat_all$solar_sample == "actual",]$resid

dat_all_2016 = dat_all %>%
  mutate(dam_hat = dam_fitted + resid) %>%
  filter(year == 2016)


formel = paste("dam_hat ~ ", formel_hour, "+ 0")
beta_actual = coef(lm(formel, data = filter(dat_all_2016, solar_sample == "actual")))
beta_2k = coef(lm(formel, data = filter(dat_all_2016, solar_sample == "solar_2k")))
beta_6k = coef(lm(formel, data = filter(dat_all_2016, solar_sample == "solar_6k")))
beta_10k = coef(lm(formel, data = filter(dat_all_2016, solar_sample == "solar_10k")))

avg_price_solar <- data.frame(
  hour = 1:24,
  actual = beta_actual,
  solar_2k = beta_2k,
  solar_6k = beta_6k,
  solar_10k = beta_10k)

rownames(avg_price_solar) = NULL

avg_price_solar

#Actual passt rest leicht nicht liegts an den residuals?? NÖ
```


```{r}

#eventuell zuerts nach solar sample splitten und seperat berechnen

dat_density = dat_all_2016

dat_density$p = seq_along(dat_density$dam_hat) - 6
dat_density$p[dat_density$p > 110] = NA


density_estimation_actual = density(filter(dat_density, solar_sample == "actual")$dam_hat, kernel = "epanechnikov" ,na.rm = TRUE , n = 110)

dat_density$dist_actual = approx(density_estimation_actual$x, density_estimation_actual$y, xout = dat_density$p)$y


density_estimation_2k = density(filter(dat_density, solar_sample == "solar_2k")$dam_hat, kernel = "epanechnikov" ,na.rm = TRUE , n = 110)

dat_density$dist_2k = approx(density_estimation_2k$x, density_estimation_2k$y, xout = dat_density$p)$y


density_estimation_6k = density(filter(dat_density, solar_sample == "solar_6k")$dam_hat, kernel = "epanechnikov" ,na.rm = TRUE , n = 110)

dat_density$dist_6k = approx(density_estimation_6k$x, density_estimation_6k$y, xout = dat_density$p)$y


density_estimation_10k = density(filter(dat_density, solar_sample == "solar_10k")$dam_hat, kernel = "epanechnikov" ,na.rm = TRUE , n = 110)

dat_density$dist_10k = approx(density_estimation_10k$x, density_estimation_10k$y, xout = dat_density$p)$y

distribution_solar = data.frame(
  "p" = -5:110,
  "density:rtm_actual" = dat_density$dist_actual[1:116],
  "density:rtm_2k" = dat_density$dist_2k[1:116],
  "density:rtm_6k" = dat_density$dist_6k[1:116],
  "density:rtm_10k" = dat_density$dist_10k[1:116]
)

distribution_solar
```

```{r}
dat_profit = dat_all_2016

for (i in 0:100) {
  dat_profit = mutate(dat_profit, !!paste("mc_", i, sep = "") := ifelse(dam_hat >= i, 1, 0))
  dat_profit = mutate(dat_profit, !!paste("pi_", i, sep = "") := ifelse(dam_hat >= i, dam_hat - i, 0))
}


dat_profit = dat_profit %>% 
  group_by(solar_sample) %>%
  summarise(across(starts_with(c("mc_", "pi_")), sum, na.rm = TRUE))

operate = as.matrix(dat_profit %>% select(starts_with("mc_")))
profit = as.matrix(dat_profit %>% select(starts_with("pi_")))

profit = t(profit)
operate = t(operate)


profit_solar = data.frame(mc = 0:100, as.data.frame(operate), as.data.frame(profit))
colnames(profit_solar) = c("mc", "operate_actual", "operate_10k", "operate_2k", "operate_6k", "profit_actual", "profit_10k", "profit_2k", "profit_6k")

profit_solar

```

Figure A20
```{r}
dotsize = 2
linesize = 0.5
color = c("blue","red","green","black")
yscale_max = 50
yscale_min = 0
step = 10

figure_a20 =  ggplot(avg_price_solar, aes(x = hour)) +
  geom_point(aes(y = actual),color = color[1], size = dotsize) +
  geom_line(aes(y = actual),color = color[1], size = linesize)+
  geom_point(aes(y = solar_2k ),color = color[2], size = dotsize) +
  geom_line(aes(y = solar_2k ),color = color[2], size = linesize)+
  geom_point(aes(y = solar_6k ),color = color[3], size = dotsize) +
  geom_line(aes(y = solar_6k ),color = color[3], size = linesize)+
  geom_point(aes(y = solar_10k),color = color[4], size = dotsize) +
  geom_line(aes(y = solar_10k),color = color[4], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "Hour", y = expression(paste("Avg. Change in Hourly Generation (MWh)"))) +
  scale_x_continuous(limits = c(1,24), breaks = 1:24) +
  scale_y_continuous(limits = c(yscale_min,yscale_max), breaks = seq(yscale_min,yscale_max,step)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))


figure_a20
```

Figure A21
```{r}

profit_solar_plot = mutate(profit_solar,
  change_profit_6k = (profit_6k-profit_2k)/profit_2k*100,
  change_profit_10k = (profit_10k-profit_2k)/profit_2k*100)

linesize = 0.5
color = c("blue","red","green","black")
yscale_max = 0
yscale_min = -16
step = 2

figure_a21 =  ggplot(profit_solar_plot, aes(x = mc)) +
  geom_line(aes(y = change_profit_6k),color = color[1], size = linesize)+
  geom_line(aes(y = change_profit_10k ),color = color[2], size = linesize)+
  geom_hline(yintercept = 0, color = "black", size = 1.2, linetype = "solid")+
  labs(x = "marginal costs", y = expression(paste(""))) +
  scale_x_continuous(limits = c(0,51), breaks = seq(0,51,5)) +
  scale_y_continuous(limits = c(yscale_min,yscale_max), breaks = seq(yscale_min,yscale_max,step)) +
  theme_classic() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.position = "none",
        panel.grid.major.y = element_line(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.margin = margin(0, 0, 0, 1, "cm"))


figure_a21

```

